Repository DB-IS-FREE/be14-1st-DB_IS_FREE-CHECK_GymPT, pull requests merged in 2025-01, with the labels that each got.

#22 다이어리 스티커 기능 추가 pr
  Diary.sql
Labels: enhancement

#33 unique, 이메일 등 유효성 검사, default 값, comment 등 추가
  HEALTH.sql
Labels: enhancement

#49 feat : 운동 장소 리뷰 등록 기능 구현
  REGIST_EXE_PLACE_REVIEW.sql
Labels: enhancement

#45 운동 장소 리뷰 삭제
  place_review delete.sql
Labels: enhancement

#54 관리자 스튜디오 정보 등록 관련 기능
  studio.sql
Labels: enhancement

#52 댓글 작성 수정 시간 컬럼명 변경
  HEALTH.sql
Labels: hotfix

#62 더미데이터 추가 생성(관리자)
  DataMaking.sql
Labels: enhancement

#59 사용자 스튜디오 정보 조회 및 키워드 기능
  studio_info.sql
Labels: enhancement

#48 운동 장소 리뷰 검색
  place_review_search.sql
Labels: enhancement

#69 hotfix/1 - 사용자 스튜디오 정보 조회 및 키워드 기능
  studio_info.sql
Labels: hotfix

#60 운동 장소 정보 검색 기능 구현
  wPlace_search.sql
Labels: enhancement

#58 커뮤니티 댓글 기능 구현
  comment_insert_update_delete.sql
Labels: enhancement

#57 feat : 댓글 조회 sql
  INQUIRY_REPLY.sql
Labels: enhancement

#75 howfix/3- 스튜디오 DML
  studio_DML.sql
Labels: hotfix

#61 운동 정보 조회 기능 구현
  workout_info_select.sql
Labels: enhancement

#51 feat : 게시글 조회 sql
  INQUIRY_COMMU_POST.sql
Labels: enhancement

#74 feature/26 - 스튜디오 리뷰 CUD 기능 구현
  studio_review_CUD.sql
Labels: enhancement

#76 Diary sub
  studio_DML.sql
Labels: hotfix

#70 feat : 운동 기록 조회및 삭제 기능 sql
  INQUIRY_EXE_RECORD.sql
Labels: enhancement

#79 doc/1 - 폴더관리 임시
  Place/place_review delete.sql
  Place/place_review_search.sql
  Place/place_review_update.sql
  StartingPackage/DataMaking.sql
  StartingPackage/HEALTH.sql
  Studio/studio.sql
  Studio/studio_DML.sql
  Studio/studio_info.sql
  Studio/studio_review_CUD.sql
  User
  User/FIND_ID.sql
  User/LEAVE.sql
  User/SIGN_UP.sql
  User/UPDATE_USER.sql
  User/USER_STATUS.sql
  test.txt
Labels: documentation

#80 hoxfix/3 - 이름 수정및 위치 조정
  Diary_DML.sql
Labels: documentation

#81 feautre/33 - 스튜디오 리뷰 CUD 커밋
  Studio/studio_review_CUD.sql
Labels: hotfix

#82 회원 더미데이터100개 생성
  HEALTH.sql
  StartingPackage/blacklist table.sql
  StartingPackage/blacklist_level table.sql
  StartingPackage/comment table.sql
  StartingPackage/community_post table.sql
  StartingPackage/diary table.sql
  StartingPackage/place_review table.sql
  StartingPackage/product table.sql
  StartingPackage/sticker table.sql
  StartingPackage/studio table.sql
  StartingPackage/studio_booking table.sql
  StartingPackage/studio_review table.sql
  StartingPackage/user table.sql
  StartingPackage/wPlace table.sql
  StartingPackage/wRecord table.sql
  StartingPackage/winfo table.sql
Labels: enhancement

#85 더미데이터 재배열
  StartingPackage/report table.sql
  StartingPackage/데이터 통합 버전.sql
Labels: enhancement

#84 feature/ 34 - 게시물 한개 조회에 따른 댓글과 대댓글 보여주는 기능 구현
  INQUIRY_COMMU_POST.sql
Labels: enhancement

#88 report 테이블 더미 데이터 수정
  StartingPackage/데이터 통합 버전.sql
Labels: enhancement

#89 관리자 3명 추가
  StartingPackage/데이터 통합 버전.sql
Labels: enhancement

#90 신고 테이블
  StartingPackage/데이터 통합 버전.sql
Labels: enhancement

#93 fix/2 - 유저 아이디,비밀번호 찾기 수정
  dummy/HEALTH.sql
  user/user_find_select.sql
Labels: bug

#94 fix/3 - 유저 회원정보 수정 기능
  user/user_update.sql
Labels: bug

#95 fix/4 - product_all_select 파일 삭제
  product/product_all_select.sql
Labels: duplicate

#97 fix/5 - 운동제품 수정기능에 url 구문 추가
  product/product_update.sql
Labels: bug

#98 테이블 DEFAULT 수정
  dummy/HEALTH.sql
Labels: enhancement

#96 feature/30 - 블랙리스트, 신고 기능 구현
  blacklist/blacklist_level_control.sql
  report/report_YN_setting.sql
  report/report_blinding.sql
  report/report_insert.sql
  report/report_post_delete.sql
Labels: enhancement

#102 feature/36 - 다이어리 회원이 조회할수 있는 기능 추가
  diary/diary_select.sql
Labels: enhancement

#101 fix : 중복된 내용의 파일 삭제
  dummy/HEALTH.sql
Labels: duplicate

#105 Feature/31 키워드로 게시물 검색
  community/post/post_keyword_select.sql
Labels: enhancement

#104 fix/6 - 운동 장소 리뷰 조회 기능 수정
  place/place_review_search.sql
Labels: duplicate

#107 feature/37 - 스튜디오 리뷰 조회 기능 구현
  studio/studio_review_search.sql
Labels: enhancement

#109 fix/7 - 게시글 1개 조회시 게시글+댓글,대댓글 조회 기능 수정
  community/comment/comment_child_select.sql
Labels: bug

#111 블랙리스트 레벨 관리 기능 핫픽스
  report/report_post_delete.sql
Labels: hotfix

#110 doc/2 - 리드미 기본 구성 초안
  README.md
Labels: documentation

#112 doc/4 - readme 기본 틀
  README.md
Labels: documentation

#113 doc/7 - 리드미 인텔리제이 이동용 2차
  README.md
Labels: documentation

#114 doc/8 - README 3차수정
  README.md
Labels: documentation

#115 doc/9 - 운동 장소 리뷰 부분 리드미 작성
  README.md
Labels: documentation

#116 doc/9 - 커뮤니티 부분 리드미 작성
  README.md
Labels: documentation

#117 fix/11 - 테케 이름 수정 및 예약 가능 여부 확인 조건 변경
  README.md
  studio/studio_booking_chk.sql
Labels: bug

#118 doc/10 - 리드미 최종전
  README.md
Labels: documentation

#119 doc/12 - README 회고록 추가
  README.md
Labels: documentation

#120 doc/12 - README 최종본
  README.md
Labels: documentation
